### ISSUE TITLE
printing with python interface

### ISSUE THREAD

**Issue by DS1705** [wolflu05/inventree-cups-plugin#2]
Are there args i'm missing or should it work like this?
this is my code:
```
def printl(stock:StockItem):
    stocklabel= LabelStock(api,pk=2)
    print(stocklabel.name)
    print('start printing')
    stock.printlabel(label=stocklabel,plugin=inventree_cups,args={})
    print(f'printed label for stock:{stock.pk}')
   
stocks=StockItem.list(api)       
print(stocks[0].getPart().name)
printl(stocks[0])
```

this is the output i get :
```
ERJ-UP3D1002V
Stock Label
start printing
Traceback (most recent call last):
  File "/home/dieter/inventree-api/inventreeInterface.py", line 149, in <module>
    printl(stocks[0])       
  File "/home/dieter/inventree-api/inventreeInterface.py", line 144, in printl
    stock.printlabel(label=stocklabel,plugin=inventree_cups,args={})
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/label.py", line 45, in printlabel
    return self._api.get(URL, params=params)
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/api.py", line 496, in get
    response = self.request(url, method='get', **kwargs)
  File "/home/dieter/env/lib/python3.8/site-packages/inventree/api.py", line 344, in request
    raise requests.exceptions.HTTPError(detail)
requests.exceptions.HTTPError: {'detail': 'Error occurred during API request', 'url': 'http://172.27.6.4:8000/api/label/stock/2/print/', 'method': 'GET', 'status_code': 404, 'body': '{"detail":"Plugin \'<module \'inventree_cups\' from \'/home/dieter/env/lib/python3.8/site-packages/inventree_cups/__init__.py\'>\' not found"}', 'headers': {'AUTHORIZATION': 'Token 813111dbeeaf7a681c1a8301ad861880df43b1e3'}, 'params': {'items[]': 2, 'plugin': <module 'inventree_cups' from '/home/dieter/env/lib/python3.8/site-packages/inventree_cups/__init__.py'>}}
```

**Comment by wolflu05** [comment]
Hello @DS1705,

have you tried to print via the inventree webinterface already? Does this work for you? (Just trying to isolate the issue you're facing)

**Comment by wolflu05** [comment]
Ah, I read your code and error message more carefully. I'm personally not familiar with the python sdk, but I guess the plugin parameter expects a string. You passed the actual plugin module (guess this is installed on your dev machine) which got stringified as the path to the __init__.py file. May you need to wrap the plugin name in "" to pass directly as a string.

**Comment by DS1705** [comment]
it works i was supposed to use the key of the plugin configuration in inventree and not the name.
Thanks for helping me with this!!

**Comment by wolflu05** [comment]
Glad to help. Have fun printing via the python sdk.
